[package]
name = "elevenlabs_rs"
version = "0.2.0"
description = "A library for interacting with ElevenLabs API"
authors = ["rwxbytes <rwxbytes@proton.me>"]
license = "MIT"
edition = "2021"
readme = "README.md"
repository = "https://github.com/rwxbytes/elevenlabs_rs"
keywords = ["elevenlabs", "tts", "text-to-speech", "voice-clone", "ai"]


[dependencies]
bytes = "1.4.0"
futures-util = "0.3.28"
reqwest = { version = "0.11.24", features = ["stream", "json", "multipart"] }
rodio = "0.17.1"
serde = { version = "1.0.173", features = ["derive"] }
serde_json = "1.0.103"
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }
