workspace = { members = ["examples/openai_websocket", "examples/pronunciation_dictionaries"] }
[package]
name = "elevenlabs_rs"
version = "0.2.0"
description = "A lib crate for ElevenLabs' AI technology"
authors = ["rwxbytes <rwxbytes@proton.me>"]
license = "MIT"
edition = "2021"
readme = "README.md"
repository = "https://github.com/rwxbytes/elevenlabs_rs"
keywords = ["elevenlabs", "tts", "text-to-speech", "voice-clone", "ai"]


[dependencies]
async-stream = "0.3.5"
base64 = "0.22.1"
bytes = "1.4.0"
futures-channel = "0.3.30"
futures-util = "0.3.28"
reqwest = { version = "0.11.24", features = ["stream", "json", "multipart"] }
rodio = "0.17.1"
serde = { version = "1.0.173", features = ["derive"] }
serde_json = "1.0.103"
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }
tokio-tungstenite = { version = "0.23.0", features = ["native-tls"] }
validator = { version = "0.18.1", features = ["derive"] }

[dev-dependencies]
twilio = "1.1.0"
axum = { version = "0.7.5", features = ["ws"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'

[[example]]
name = "basic_twilio"
path = "examples/basic_twilio.rs"

